import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className='text-4xl text-black text-center'>SS PROGRAMS</h1>
      <h1 className='text-4xl text-black text-center'>
      <Link className='text-2xl text-black text-center' href="/ss1">Operation on Matrices</Link>
      </h1>
      <h1 className='text-4xl text-black text-center'>
      <Link className='text-2xl text-black text-center' href="/ss2">Impulse Step Sine</Link>
      </h1>
      <h1 className='text-4xl text-black text-center'>
      <Link className='text-2xl text-black text-center' href="/ss3">Square ,sawtooth ,sinc ,triangular</Link>
      </h1>
      <h1 className='text-4xl text-black text-center'>
      <Link className='text-2xl text-black text-center' href="/ss4">Operations on signals</Link>
      </h1>
      <h1 className='text-4xl text-black text-center'>
      <Link className='text-2xl text-black text-center' href="/ss5">Delayed Advanced Folded</Link>
      </h1>
      <h1 className='text-4xl text-black text-center'>
      <Link className='text-2xl text-black text-center' href="/ss6">Energy Power of Signal</Link>
      </h1>
      <h1 className='text-4xl text-black text-center'>
      <Link className='text-2xl text-black text-center' href="/ss7">Folded Even Odd</Link>
      </h1>
      <h1 className='text-4xl text-black text-center'>
      <Link className='text-2xl text-black text-center' href="/ss8">Real Imaginary</Link>
      </h1>
      <h1 className='text-4xl text-black text-center'>
      <Link className='text-2xl text-black text-center' href="/ss9">Convolution of signals</Link>
      </h1>
      <h1 className='text-4xl text-black text-center'>
      <Link className='text-2xl text-black text-center' href="/ss10">Auto & Cross correlation</Link>
      </h1>
      <h1 className='text-4xl text-black text-center'>
      <Link className='text-2xl text-black text-center' href="/ss11">Linearity</Link>
      </h1>
      <h1 className='text-4xl text-black text-center'>
      <Link className='text-2xl text-black text-center' href="/ss12">Time Variance</Link>
      </h1>
      <h1 className='text-4xl text-black text-center'>
      <Link className='text-2xl text-black text-center' href="/ss13">computation of unit sample unit step and sine and verify physical</Link>
      </h1>
      <h1 className='text-4xl text-black text-center'>
      <Link className='text-2xl text-black text-center' href="/ss14">Gibbs Phenomenon</Link>
      </h1>
      <h1 className='text-4xl text-black text-center'>
      <Link className='text-2xl text-black text-center' href="/ss15">Fourier Transform Magnitude and phase spectrum</Link>
      </h1>
      <h1 className='text-4xl text-black text-center'>
      <Link className='text-2xl text-black text-center' href="/ss16">waveform synthesis using laplace transform</Link>
      </h1>
      <h1 className='text-4xl text-black text-center'>
      <Link className='text-2xl text-black text-center' href="/ss17">Sampling theorm</Link>
      </h1>
      
    </>
  )
}
