import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className='text-4xl text-black text-center'>SS PROGRAMS</h1>
      <h1 className='text-4xl text-black text-center'>
      <Link className='text-2xl text-black text-center' href="https://wtools.io/paste-code/bJNL">Operation on Matrices</Link>
      </h1>
      <h1 className='text-4xl text-black text-center'>
      <Link className='text-2xl text-black text-center' href="https://wtools.io/paste-code/bJNM">Impulse Step Sine</Link>
      </h1>
      <h1 className='text-4xl text-black text-center'>
      <Link className='text-2xl text-black text-center' href="https://wtools.io/paste-code/bJOj">Square ,sawtooth ,sinc ,triangular</Link>
      </h1>
      <h1 className='text-4xl text-black text-center'>
      <Link className='text-2xl text-black text-center' href="https://wtools.io/paste-code/bJOl">Operations on signals</Link>
      </h1>
      <h1 className='text-4xl text-black text-center'>
      <Link className='text-2xl text-black text-center' href="https://wtools.io/paste-code/bJOn">Delayed Advanced Folded</Link>
      </h1>
      <h1 className='text-4xl text-black text-center'>
      <Link className='text-2xl text-black text-center' href="https://wtools.io/paste-code/bJOo">Energy Power of Signal</Link>
      </h1>
      <h1 className='text-4xl text-black text-center'>
      <Link className='text-2xl text-black text-center' href="https://wtools.io/paste-code/bJOs">Folded Even Odd</Link>
      </h1>
      <h1 className='text-4xl text-black text-center'>
      <Link className='text-2xl text-black text-center' href="https://wtools.io/paste-code/bJOt">Real Imaginary</Link>
      </h1>
      <h1 className='text-4xl text-black text-center'>
      <Link className='text-2xl text-black text-center' href="https://wtools.io/paste-code/bJOu">Convolution of signals</Link>
      </h1>
      <h1 className='text-4xl text-black text-center'>
      <Link className='text-2xl text-black text-center' href="https://wtools.io/paste-code/bJOw">Auto & Cross correlation</Link>
      </h1>
      <h1 className='text-4xl text-black text-center'>
      <Link className='text-2xl text-black text-center' href="https://wtools.io/paste-code/bJOx">Linearity</Link>
      </h1>
      <h1 className='text-4xl text-black text-center'>
      <Link className='text-2xl text-black text-center' href="https://wtools.io/paste-code/bJOy">Time Variance</Link>
      </h1>
      <h1 className='text-4xl text-black text-center'>
      <Link className='text-2xl text-black text-center' href="https://wtools.io/paste-code/bJOz">computation of unit sample unit step and sine and verify physical</Link>
      </h1>
      <h1 className='text-4xl text-black text-center'>
      <Link className='text-2xl text-black text-center' href="https://wtools.io/paste-code/bJO0">Gibbs Phenomenon</Link>
      </h1>
      <h1 className='text-4xl text-black text-center'>
      <Link className='text-2xl text-black text-center' href="https://wtools.io/paste-code/bJO3">Fourier Transform Magnitude and phase spectrum</Link>
      </h1>
      <h1 className='text-4xl text-black text-center'>
      <Link className='text-2xl text-black text-center' href="https://wtools.io/paste-code/bJO4">waveform synthesis using laplace transform</Link>
      </h1>
      <h1 className='text-4xl text-black text-center'>
      <Link className='text-2xl text-black text-center' href="https://wtools.io/paste-code/bJO5">Sampling theorm</Link>
      </h1>
      
    </>
  )
}
